# Generated by Django 5.2.17 on 2026-08-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_file', models.FileField(upload_to='notes/')),
                ('file_type', models.CharField(max_length=10)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
    ]
