# Generated by Django 5.2.17 on 2026-08-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='education_level',
            field=models.CharField(blank=True, default='', help_text='Class 3, Class 12, MBBS, B.Tech, UPSC, Self-Learner', max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='subject_domain',
            field=models.CharField(blank=True, default='', help_text='Physics, Anatomy, Accounting, DSA, Constitutional Law, EVS', max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
