# Generated by Django 5.2.17 on 2026-08-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_education_level_note_subject_domain_note_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Syllabus', max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_file', models.FileField(upload_to='syllabi/')),
                ('file_type', models.CharField(max_length=10)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('parsed_units', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
    ]
