# Generated by Django 5.2.17 on 2026-08-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceKnowledgeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('syllabus_title', models.CharField(blank=True, default='', max_length=255)),
                ('chapter_title', models.CharField(blank=True, default='', max_length=255)),
                ('topic_name', models.CharField(blank=True, default='', max_length=255)),
                ('structured_profile', models.JSONField(default=dict)),
                ('source_type', models.CharField(default='academic_curriculum', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
